pool:
  vmImage: 'ubuntu-16.04'
trigger:
  - master 
steps:
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(buils.artifactstagingdirectory)/Templates'
    inputs: 
      SourceFolder: deployment
      Contents: '*.json'
      TargetFolder:  $(buils.artifactstagingdirectory)/Templates
  - task: Npm@1
    displayName: 'npm custom'
    inputs:
      command: custom 
      verbose: false
      customCommand: 'install --production'
  - task: ArchiveFiles@2
    displayName : 'Archive $(Build.SourceDirectory)'
    inputs:
      rootFolderOrFile: '$(Build.SourceDirectory'
      includeRootFolder: false
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
